// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingRequest struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type PingResponse struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// #################################
//          Shared Messages
// #################################
type ByIDRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByIDRequest) Reset()         { *m = ByIDRequest{} }
func (m *ByIDRequest) String() string { return proto.CompactTextString(m) }
func (*ByIDRequest) ProtoMessage()    {}
func (*ByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *ByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByIDRequest.Unmarshal(m, b)
}
func (m *ByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByIDRequest.Marshal(b, m, deterministic)
}
func (m *ByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByIDRequest.Merge(m, src)
}
func (m *ByIDRequest) XXX_Size() int {
	return xxx_messageInfo_ByIDRequest.Size(m)
}
func (m *ByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ByIDRequest proto.InternalMessageInfo

func (m *ByIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type LoadKeyRequest struct {
	Keys                 []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadKeyRequest) Reset()         { *m = LoadKeyRequest{} }
func (m *LoadKeyRequest) String() string { return proto.CompactTextString(m) }
func (*LoadKeyRequest) ProtoMessage()    {}
func (*LoadKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *LoadKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadKeyRequest.Unmarshal(m, b)
}
func (m *LoadKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadKeyRequest.Marshal(b, m, deterministic)
}
func (m *LoadKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadKeyRequest.Merge(m, src)
}
func (m *LoadKeyRequest) XXX_Size() int {
	return xxx_messageInfo_LoadKeyRequest.Size(m)
}
func (m *LoadKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadKeyRequest proto.InternalMessageInfo

func (m *LoadKeyRequest) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

// #################################
//
// #################################
type Response struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Response) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "bobbynodb.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "bobbynodb.PingResponse")
	proto.RegisterType((*ByIDRequest)(nil), "bobbynodb.ByIDRequest")
	proto.RegisterType((*LoadKeyRequest)(nil), "bobbynodb.LoadKeyRequest")
	proto.RegisterType((*Response)(nil), "bobbynodb.Response")
	proto.RegisterType((*CreateRequest)(nil), "bobbynodb.CreateRequest")
	proto.RegisterType((*UpdateRequest)(nil), "bobbynodb.UpdateRequest")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0x6d, 0x56, 0x8a, 0x7b, 0xb3, 0x43, 0x22, 0x68, 0x19, 0x08, 0x33, 0x7a, 0xf0, 0xd4,
	0x83, 0x13, 0x86, 0xd7, 0x3a, 0x10, 0x51, 0x44, 0x26, 0x5e, 0xbc, 0x25, 0xe6, 0x21, 0x45, 0x6d,
	0x6a, 0x13, 0x85, 0xfe, 0x57, 0xfe, 0x89, 0x92, 0x66, 0x1b, 0x89, 0x3a, 0xd0, 0xdb, 0xa3, 0xfd,
	0x7d, 0xdf, 0xfb, 0xde, 0xd7, 0x42, 0xaa, 0xb1, 0xf9, 0x28, 0x1f, 0x31, 0xaf, 0x1b, 0x65, 0x14,
	0xed, 0x0b, 0x25, 0x44, 0x5b, 0x29, 0x29, 0xd8, 0x01, 0x0c, 0x6e, 0xcb, 0xea, 0x69, 0x8e, 0x6f,
	0xef, 0xa8, 0x0d, 0xa5, 0x10, 0x4b, 0x6e, 0x78, 0x16, 0x8d, 0xa3, 0xe3, 0xfe, 0xbc, 0x9b, 0x19,
	0x83, 0x2d, 0x87, 0xe8, 0x5a, 0x55, 0x1a, 0x7f, 0x65, 0xf6, 0x61, 0x50, 0xb4, 0x97, 0xb3, 0xa5,
	0xcd, 0x10, 0x48, 0x29, 0x17, 0x00, 0x29, 0x25, 0x3b, 0x82, 0xe1, 0xb5, 0xe2, 0xf2, 0x0a, 0x5b,
	0x6f, 0xd1, 0x33, 0xb6, 0x3a, 0x8b, 0xc6, 0x3d, 0x6b, 0x62, 0x67, 0x96, 0xc3, 0xe6, 0x6a, 0xc9,
	0x37, 0x07, 0xcb, 0x57, 0xfc, 0x15, 0x33, 0xe2, 0x96, 0xda, 0x99, 0x1d, 0x42, 0x7a, 0xde, 0x20,
	0x37, 0xe8, 0x99, 0x76, 0x50, 0xe4, 0x41, 0x13, 0x48, 0xef, 0x6b, 0xe9, 0x41, 0x7f, 0x70, 0x3e,
	0xf9, 0x24, 0xb0, 0x5d, 0xd8, 0x8e, 0x6e, 0x94, 0x14, 0x77, 0xae, 0x3b, 0x3a, 0x85, 0xd8, 0xf6,
	0x40, 0x77, 0xf3, 0x55, 0x7d, 0xb9, 0xd7, 0xdd, 0x68, 0xef, 0xc7, 0xf3, 0xc5, 0x2d, 0x67, 0x90,
	0xb8, 0x9c, 0x34, 0xf3, 0x90, 0x20, 0xfa, 0x68, 0xc7, 0x7b, 0xb3, 0x14, 0xb2, 0x0d, 0x2b, 0x75,
	0xe9, 0x03, 0x69, 0x70, 0xd0, 0x3a, 0xe9, 0x14, 0x92, 0x19, 0xbe, 0xa0, 0xc1, 0x20, 0xb0, 0xf7,
	0x95, 0xd6, 0x09, 0x4f, 0xa1, 0x77, 0x81, 0xe6, 0x9f, 0xaa, 0x22, 0x7e, 0x20, 0xb5, 0x10, 0x49,
	0xf7, 0x83, 0x4d, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xef, 0x18, 0x82, 0x71, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BobbyNodbServiceClient is the client API for BobbyNodbService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BobbyNodbServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Response, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*Response, error)
	Delete(ctx context.Context, in *ByIDRequest, opts ...grpc.CallOption) (*Response, error)
	Get(ctx context.Context, in *ByIDRequest, opts ...grpc.CallOption) (*Response, error)
}

type bobbyNodbServiceClient struct {
	cc *grpc.ClientConn
}

func NewBobbyNodbServiceClient(cc *grpc.ClientConn) BobbyNodbServiceClient {
	return &bobbyNodbServiceClient{cc}
}

func (c *bobbyNodbServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/bobbynodb.BobbyNodbService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bobbyNodbServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/bobbynodb.BobbyNodbService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bobbyNodbServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/bobbynodb.BobbyNodbService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bobbyNodbServiceClient) Delete(ctx context.Context, in *ByIDRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/bobbynodb.BobbyNodbService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bobbyNodbServiceClient) Get(ctx context.Context, in *ByIDRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/bobbynodb.BobbyNodbService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BobbyNodbServiceServer is the server API for BobbyNodbService service.
type BobbyNodbServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Create(context.Context, *CreateRequest) (*Response, error)
	Update(context.Context, *UpdateRequest) (*Response, error)
	Delete(context.Context, *ByIDRequest) (*Response, error)
	Get(context.Context, *ByIDRequest) (*Response, error)
}

// UnimplementedBobbyNodbServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBobbyNodbServiceServer struct {
}

func (*UnimplementedBobbyNodbServiceServer) Ping(ctx context.Context, req *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedBobbyNodbServiceServer) Create(ctx context.Context, req *CreateRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedBobbyNodbServiceServer) Update(ctx context.Context, req *UpdateRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedBobbyNodbServiceServer) Delete(ctx context.Context, req *ByIDRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedBobbyNodbServiceServer) Get(ctx context.Context, req *ByIDRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterBobbyNodbServiceServer(s *grpc.Server, srv BobbyNodbServiceServer) {
	s.RegisterService(&_BobbyNodbService_serviceDesc, srv)
}

func _BobbyNodbService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BobbyNodbServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bobbynodb.BobbyNodbService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BobbyNodbServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BobbyNodbService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BobbyNodbServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bobbynodb.BobbyNodbService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BobbyNodbServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BobbyNodbService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BobbyNodbServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bobbynodb.BobbyNodbService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BobbyNodbServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BobbyNodbService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BobbyNodbServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bobbynodb.BobbyNodbService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BobbyNodbServiceServer).Delete(ctx, req.(*ByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BobbyNodbService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BobbyNodbServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bobbynodb.BobbyNodbService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BobbyNodbServiceServer).Get(ctx, req.(*ByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BobbyNodbService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bobbynodb.BobbyNodbService",
	HandlerType: (*BobbyNodbServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _BobbyNodbService_Ping_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _BobbyNodbService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _BobbyNodbService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BobbyNodbService_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _BobbyNodbService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
